### ISSUE TITLE
Integrate color definitions

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#131]
Colors are defined in https://www.figma.com/file/uKl9JwV0keZGoaB1DeAXfE/Incoming-Design-System?node-id=13%3A31210&t=yEvjd3eHIW41rrIu-0

Colors that need to be adjusted/doublechecked:
- [ ] NAC avalanche colors - are these in sync? Doesn't seem like it, Figma has considerable as `rgba(234, 152, 63, 1)` while code has it as `rgb(247, 148, 30)`
- [ ] Weather forecast tab: SmallHeaderWithTooltip text needs to be `UI/NWAC-dark`

To push this even further:
- [ ] Remove old NativeBase color definitions as much as possible and replace them with defined colors from the NWAC palette
- [ ] Change typedefs of color props on our View wrapper so that they only accept named colors

**Comment by stevekuznetsov** [comment]
@floatplane the NAC avalanche colors I stole from the web-app - are the ones in Figma right?

**Comment by floatplane** [comment]
don't know! we should track down the discrepancy. did you steal from the NAC web app or the NWAC web app (which I guess uses the widget supplied by NAC)

**Comment by floatplane** [comment]
@stevekuznetsov where exactly did you steal them from? the colors in our code don't exactly match the colors in the scale at the bottom of https://avalanche.org/#/current, either. (they are very close, though - so maybe they were tweaked over time, or maybe NAC isn't perfectly consistent everywhere)

**Comment by stevekuznetsov** [comment]
/shrug - I think I just copy-pasted from one of the scales or encylopedia entries, can't be certain which. I can go ahead and update those copies from whichever source, and write it down this time to help folks in the future.

**Comment by floatplane** [comment]
I think I'm closing this particular issue and we'll revisit colors + theming with a potential tamagui integration
