### ISSUE TITLE
Image pan and zoom wonkiness

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#235]
I will probably end up trying to fix the library, gathering issues I've noticed so far:

- [ ] when zoomed in, you can pan the image further than you should be able to - you can get the edge of the image all the way up in the middle of the screen
- [ ] on android, double tapping on the first image you see does nothing. but if you swipe to the next image and then come back, double-tap to zoom starts working. haven't cross-checked iOS on this one

**Comment by rustynwac** [comment]
Appears to be done. Rusty/Charlotte testing
