### ISSUE TITLE
App freezing after being open for a while - can scroll but cant click anything

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#249]
what I have observed is if the app is left open in a backgorund on a page other than the map, say avalanche forecast or weather stations, when the app is opened, I can scroll up and down but not able to push any buttons on the page. Scrolling is the only action to do so to use the app normally, the app needs to be killed and re-loaded. Existing the app to go to another app and navigating back doesnt do anything.

**Comment by yuliadub** [comment]
havent noticed this recently - so may be a non issue. Will watch for it for the next few weeks and if it doesnt up again I will close

**Comment by yuliadub** [comment]
so this has stopped happening, but a new similar thing is: if the app is open in the background for a while, when I go to open it I just get a blank white screen :/ so it does seem like something makes it throw an exception when its running in the background is my guess. I looked around on Sentry if there were any errors that could be related but didnt find anything.

**Comment by yuliadub** [comment]
may be worth all of you trying to see if your app gives you a white screen if you open it then leave it running in the background (without shutting off your phone) for over 24 hours and the trying to open it again?

**Comment by stevekuznetsov** [comment]
@yuliadub are you still seeing this?

**Comment by yuliadub** [comment]
have not seen this, going to close.
