### ISSUE TITLE
[sentry] No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#258]
https://nwac.sentry.io/issues/3958798109/?project=4504317393436672&query=is%3Aunresolved&referrer=issue-stream

Seems to be happening only on IOS.

was looking at somewhat related convos:
https://github.com/expo/expo/issues/7689
https://github.com/expo/expo/issues/20958

**Comment by mangowi** [comment]
still an issue expo 48 iOS bare-workflow

**Comment by krisgerhard** [comment]
still an issue expo 48 iOS managed-workflow

**Comment by floatplane** [comment]
I am hopeful this is fixed in #360
