### ISSUE TITLE
Set up mixpanel

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#282]

**Comment by yuliadub** [comment]
https://github.com/stevekuznetsov/avalanche-forecast/pull/283

**Comment by floatplane** [comment]
@yuliadub do you want to try and bring #283 back to life?

also found this, if we want to use the official sdk without causing Expo Go to explode: https://github.com/mixpanel/mixpanel-react-native/issues/82#issuecomment-1421703731

**Comment by floatplane** [comment]
I am working on this now
