### ISSUE TITLE
Update to Expo 47

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#3]
https://blog.expo.dev/expo-sdk-47-a0f6f5c038af

Build targets will need to be updated
> **SDK 47 does not support classic builds.** [SDK 46 was the final release to support](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60) `[expo build:[ios|android]](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60)`. You can build your Expo projects with [EAS Build](https://docs.expo.dev/build/introduction/) ([in the cloud](https://docs.expo.dev/build/setup/) or [on your own infrastructure](https://docs.expo.dev/build-reference/local-builds/)), or through Xcode/Android Studio (run [prebuild](https://docs.expo.dev/workflow/prebuild/) to generate the native projects).

**Comment by stevekuznetsov** [comment]
Everything I've done so far has been with EAS build so hopefully there's minimal churn there!

**Comment by stevekuznetsov** [comment]
@floatplane I did this in #27
