### ISSUE TITLE
Reset zoom if the map is moved

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#304]
Today if a map is moved accidentally (since moving of the map is allowed) there is no easy way to set it to be back to its default (i.e. in the center as when it was when the app was first opened) It would be good to either not allow the user to move the map at all or add a button to let the user renavigate the map to its original position.

**Comment by stevekuznetsov** [comment]
@charlotteguard any thoughts on whether we should allow or disallow the pinch-to-zoom features on the map screen?

**Comment by floatplane** [comment]
the map resets itself when you tap a card in the bottom, I'm not sure we need anything more than that for v1? but this is also a new feature request, so it should go through Asana and the designers so they can think through the right behavior!

**Comment by charlotteguard** [comment]
yeah maybe we think through patterns for this especially since the most common one I can think of is the location icon which isn't curranty part of the experience. I added this to the open questions asana board - https://app.asana.com/0/1203776156197304/1205742988383609/f
