### ISSUE TITLE
Add ability to dismiss cards with forecast by touching outside the zone

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#305]
There is no way currently to dismiss the cards from the map view, they only can be swiped towards the bottom where half of the card is still visible. It would be good to add functionality to dismiss the card if the screen outside the card (not another zone) is tapped

**Comment by floatplane** [comment]
This is really a design request (and I did ask a while ago if we wanted the behavior you're describing and the answer at the time was "no")
