### ISSUE TITLE
Outcomes Not Styled Well

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#313]
We have an `<Outcome/>` component and a number of permutations of these, but they are not styled well. When they take up a whole page, they are often not centered correctly. When they are added inline, they do not look like they flow with the page, etc.

**Comment by floatplane** [comment]
@stevekuznetsov do you have some screenshots, or pointers on how to get the app into the states you're describing?

**Comment by stevekuznetsov** [comment]
![File (5)](https://github.com/stevekuznetsov/avalanche-forecast/assets/7328370/0fdca26f-bc4a-427d-935c-e12e41496e01)


@floatplane here's an example of this. The colors look all goofy here.

**Comment by charlotteguard** [comment]
@stevekuznetsov when you say the colors are goofy - do you mean the grey box? Maybe we have design weigh in on what this is supposed to look like?

**Comment by stevekuznetsov** [comment]
Yes - it's just a weird grey box halfway into the screen.

**Comment by floatplane** [comment]
fixed in #457
