### ISSUE TITLE
Probably need to blow away query cache across installs

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#324]
Here's a scenario that can get you into trouble:

- change the return value of a method like `fetchNWACObservations` to include some new fields in the result
- try to run the code
- observe that useQuery will happily return a previously cached result that does not include your new fields 😬 

There's probably elaborate solutions to this involving schema versioning and selectively invalidating cache results, but the simple solution is probably to just nuke the cache whenever the app version changes.

**Comment by stevekuznetsov** [comment]
Yeah, agreed. Or a simple integer counter for schema revision - the rate of change for those is super slow. I don't know that users will ever notice us blowing the whole thing away though, just a slightly slower startup time.
