### ISSUE TITLE
Observation Date Selector Styling Off

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#334]
![File (6)](https://github.com/stevekuznetsov/avalanche-forecast/assets/7328370/7137ace8-fc7b-4f7e-8c26-ea2b15f5e17f)

**Comment by floatplane** [comment]
did this ever work? on the one hand, I synced back to https://github.com/stevekuznetsov/avalanche-forecast/commit/ee7cea93 and it still looked broken. on the other hand, I'm pretty sure I've seen it working ok at some point in the past few weeks. 😕
