### ISSUE TITLE
Changing Date Range in Observations Does Not Cause Re-Load

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#335]
What I did:

1. open app
2. go to observations, "view all"
3. enter a custom date range
4. let the app show me them
5. edit the "published after" date to an earlier time point
6. see no changes

cc @floatplane

**Comment by stevekuznetsov** [comment]
Looks like I needed to reset the cache entirely to fix this, restarting the app did not help.

**Comment by floatplane** [comment]
There's currently a hard-coded limit of 90 days back from the end date, despite whatever you pick in custom dates. The custom date picker doesn't enforce this so it's confusing. (The custom date picker doesn't enforce anything, really)
