### ISSUE TITLE
Debug Menu - Map With Active Warning Incorrect

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#353]
For some reason we're loading the wrong avalanche forecasts for this - we have flashing considerable zones, which should be high...

cc @floatplane

**Comment by floatplane** [comment]
I think we flash whenever there's an active warning for a zone, regardless of danger level. We may have picked a strange time at the intersection of forecast publishing date/warning publishing date?

Just to confirm, is this the one you're talking about?
https://github.com/NWACus/avy/blob/c2978b3889594cdf622b07ddc540c54a4febf5f0/components/screens/MenuScreen.tsx#L300-L301

**Comment by stevekuznetsov** [comment]
Yes, I think your analysis is correct - we are loading the wrong forecasts but the right warning.

**Comment by stevekuznetsov** [comment]
This is fixed in #696
