### ISSUE TITLE
Warnings / Watches / Bulletins Layout Incorrect

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#354]
This used to be correct but the padding is all messed up now :(

![File (9)](https://github.com/stevekuznetsov/avalanche-forecast/assets/7328370/61616ef6-c9b7-408b-93e4-658179381a7a)

cc @floatplane

**Comment by stevekuznetsov** [comment]
This looks fine on the Test Flight build but not from `main` - maybe a recent regression?

**Comment by floatplane** [comment]
Are you looking at this the "normal" way (set a browsing date, click on the map) or straight from the debug menu? I don't repro:

![image](https://github.com/NWACus/avy/assets/101196/280c39f8-c34c-42ca-834e-7b144c8a1647)

**Comment by stevekuznetsov** [comment]
@floatplane I was looking at it by using the debug menu which links to those dates.
