### ISSUE TITLE
404 Error Messages Goofy

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#356]
Dev menu - "view a forecast we can't find" gives me

![File (10)](https://github.com/NWACus/avy/assets/7328370/512276b6-fff4-4f1e-98d4-8b02939c6ec5)

@floatplane

**Comment by stevekuznetsov** [comment]
![File (11)](https://github.com/NWACus/avy/assets/7328370/f83ba3be-1198-4568-b75a-44b93e8251e8)


Oops, wrong image but similar error

**Comment by floatplane** [comment]
fixed in #457
