### ISSUE TITLE
Crisp Up App Version -> Commit Transform

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#358]
The code I wrote last year to use app metadata to determine the commit that built it does not work any longer as some of the inputs we need do not seem to be exposed by Expo any longer - https://github.com/NWACus/avy/blob/34442bd1a2f2d62c49e48ba71607c8c8fdb36f52/components/screens/MenuScreen.tsx#L811-L812

**Comment by stevekuznetsov** [comment]
cc @floatplane

**Comment by floatplane** [comment]
I think we should just modify the build scripts to set an environment variable with the current head SHA and embed that in the JS bundle - seems much easier

**Comment by stevekuznetsov** [comment]
It does look like `$EAS_BUILD_GIT_COMMIT_HASH` is [exposed](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables) - I think the tricky one last I checked was `eas update` for OTA updates. Let me look into that.

**Comment by floatplane** [comment]
You would still have to copy that value into a variable that's accessible from the phone binary - most environment variables are stripped and not accessible from `process.env`.

Something prefixed with `EXPO_PUBLIC` is automatically available, so a slight tweak to the build scripts should do it:
```
EXPO_PUBLIC_GIT_HASH=$(git rev-parse --short HEAD) eas update <blah blah blah>
```

**Comment by floatplane** [comment]
grabbing this one as it's becoming harder to track what's in which build
