### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#379]
Avalanche education (learn) goes to "about" but should go here: https://nwac.us/avalanche-education/
Membership: https://nwac.us/membership/
Volunteer: https://support.nwac.us/volunteer/
I think support can be combined with memberships? And be called "become a member" or "donate" or "support" ... I can't decide what the right one is right at the moment.
latest news: can we link to a section on the website? Or just the URL? news lives on the [www.nwac.us](https://www.nwac.us/) homepage

**Comment by floatplane** [comment]
not really up to us to make a final decision 😄 i just stubbed in a few things that seemed reasonable

https://github.com/NWACus/avy/blob/f35c53a6de01a4f4e5937f2ca8d7e0cd5773d0c6/data/settingsMenuItems.ts#L24-L37

**Comment by stevekuznetsov** [comment]
Yes, sorry, not asking for you to make a decision, just whether the royal we had made one :)

**Comment by floatplane** [comment]
Ah, not that I know of! I think @charlotteguard was in charge of tracking the things we need from SNFAC:

1. square logo (unless the one we hacked in works)
2. the app links above
3. description shown in the center picker
4. ...anything else I'm forgetting?

It might be easier to get further along and ask for all the things at once, as opposed to having a bunch of separate email threads to track.

**Comment by floatplane** [comment]
closing this issue as the original work is completed - we'll track the SNFAC stuff separately
