### ISSUE TITLE
Timezone woes on Android

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#380]
We are getting errors thrown here: https://github.com/NWACus/avy/blob/e260db25afe3e9003dc08277768071def1d836f1/utils/date.ts#L4-L10

Example message: `Failed to format date: Invalid time value, Fri Sep 22 2023 23:58:15 GMT+0000, yyyy-MM-dd, America/Los_Angeles`

Because we're using Hermes, I *think* that this should Just Work, but clearly something isn't right. This only happens on Android (and only on one device so far).

Ideas:
1. Remove `date-time-format-timezone` polyfill
2. Look at thread from dayjs: https://github.com/iamkun/dayjs/issues/1377
3. Add more polyfills from @formatjs?
4. ...?

**Comment by floatplane** [comment]
Maybe we don't even need timezone names? I don't think we display them anywhere. Can we just use `Date.getTimezoneOffset()` to convert between UTC <=> local time and skip this craziness?

**Comment by stevekuznetsov** [comment]
I'm in favor of whatever has us owning the smallest amount of custom code... what a mess.

**Comment by stevekuznetsov** [comment]
@floatplane fixed in https://github.com/NWACus/avy/pull/481 ?

**Comment by floatplane** [comment]
Let's give it a few days to bake before resolving

**Comment by floatplane** [comment]
this does seem fixed 😅
