### ISSUE TITLE
Obs submission not working

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#405]
It keeps spinning on submission page with Cancel submission button and spinny wheel. If I navigate away from that tab and come back to it later, the state doesnt seem to change.  (I can also edit fields in the submission which I probably shouldn't be able to do?)

if I click the back button next to "submit observation" header at the top of page that takes me back to the main obs screen and if I go to submit a new obs my previous one appears to have been lost.

**Comment by stevekuznetsov** [comment]
You get no toasts showing up, right?

**Comment by yuliadub** [comment]
correct, no other screens just the spinning symbol on the cancel button

**Comment by floatplane** [comment]
> (I can also edit fields in the submission which I probably shouldn't be able to do?)
I created #428 to track this separately

**Comment by floatplane** [comment]
The bad submission behavior should be fixed in #424 . I suspect the base issue here was that we weren't supplying the new `obs_source` param which became required.
