### ISSUE TITLE
Obs zone name filter gets caught off in filter list

### ISSUE THREAD

**Issue by yuliadub** [NWACus/avy#407]
I later realized that I can scroll to the right to view those, so maybe this is by design but if I wouldnt have figured out that I can scroll the terms to the right I would have thought this was broken. 

![File (1)](https://github.com/NWACus/avy/assets/9418602/a0fec459-4a85-4430-8b9c-6b8fe997e856)

**Comment by floatplane** [comment]
@yuliadub let's flag this as a design question in Asana. The code solution isn't clear to me - one answer would be to add a shadow to the end indicating that there's more to see...but another solution would be to change the interface to something completely different, and I just don't know what the designers would be preferring here. It's possible that the filter interface gets stripped down.
