### ISSUE TITLE
Add online/offline detection to ObservationUploader

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#426]
Follow-on work from #424 - we should pause the upload queue when offline, and resume it when online.

**Comment by stevekuznetsov** [comment]
@floatplane I think we had this at some point in the past already - see [`useAppState()`](https://github.com/NWACus/avy/blob/main/hooks/useAppState.ts).  The other half would be a configuration option for [`tanstack-query`](https://tanstack.com/query/v4/docs/react/guides/network-mode).

**Comment by floatplane** [comment]
I went with `NetInfo` since it seems to be [blessed by Expo](https://docs.expo.dev/versions/latest/sdk/netinfo/)
