### ISSUE TITLE
Revisit use of `staleTime`?

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#474]
We are doing this almost everywhere we use `useQuery`:
```
    staleTime: 24 * 60 * 60 * 1000, // don't bother re-fetching for one day (in milliseconds)
```
and I'm worried that it's not that helpful - and potentially harmful, in the case where overly stale data gets stuck in the cache. 

My reading of the `useQuery` docs is that you can crank this value down quite low and the library will do the right thing, defined as:
1. immediately return you any cached data that it has
2. try to refetch stale queries async when staleTIme has elapsed, and then potentially trigger a re-render with new data

The creator has a [blog post](https://tkdodo.eu/blog/practical-react-query#the-defaults-explained) that talks about this, and he also replied to a [StackOverflow post](https://stackoverflow.com/questions/72828361/what-are-staletime-and-cachetime-in-react-query). Both of those make me think that we should just leave `staleTime` set to the default.

@stevekuznetsov let me know what you think of the above. is there a particular problem that you were thinking of that led you to choosing a 24 hour `staleTime` value?

**Comment by stevekuznetsov** [comment]
Only intent was to reduce load on the NAC server for semi-static data like the center metadata, polygons, list of weather stations. Agreed that even with the default (immediate) staleness configuration our users will get the right render behavior, I just didn't feel like we needed to send NAC all those requests, but if it's possibly harmful when we incorrectly guess the static-ness of the data, agreed that we would prefer to just use the shorter time-frame.
