### ISSUE TITLE
Android 6 issues in Sentry

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#475]
assuming there's agreement on bumping our minimum version to Android 8, we can set the `minSdkVersion` to `26` ([source](https://en.wikipedia.org/wiki/Android_Oreo)) via the [`expo-build-properties` plugin](https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeandroid).

if there's no agreement then 🤷 I guess someone has to go find an old Nexus phone and get busy

**Comment by stevekuznetsov** [comment]
If [this](https://endoflife.date/android) is to be believed, everything older than Android 11 is EOL - do we have any reason to support those?

**Comment by floatplane** [comment]
I think the reason is the product tradeoff between maximizing reach and minimizing your support matrix. According to that [chart](https://gs.statcounter.com/android-version-market-share/all/united-states-of-america) I shared in Slack, around 79% of Android devices in the US are running Android 11 or greater, which on the surface is not great - but then again, who knows how many of those 21% are FireTVs or POS terminals or whatever 🤷 . 

Someone with more Android experience/holistic product sense than me would need to make that call. I would put the question to Zach in the [Slack thread](https://nwactechcommittee.slack.com/archives/C03BXSN6Z5F/p1698160568376459).

FWIW the corresponding [iOS chart](https://gs.statcounter.com/ios-version-market-share/all/united-states-of-america) is wonderfully simple: basically everyone is on iOS 15+.
