### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#496]
We've got a couple of these in Sentry
https://nwac.sentry.io/issues/4577668605/?project=4504317393436672&query=is:unresolved&stream_index=0
https://nwac.sentry.io/issues/4577466920/?project=4504317393436672&query=is:unresolved&stream_index=5

Also anecdotal reports of the app behaving weirdly when it runs for a long time make me believe that we might be leaking somewhere. 

This looks like a good place to start: https://blog.swmansion.com/hunting-js-memory-leaks-in-react-native-apps-bd73807d0fde

**Comment by stevekuznetsov** [comment]
xref https://github.com/NWACus/avy/issues/249

**Comment by floatplane** [comment]
so far there's only 1 instance of each error in Sentry in the last 30 days, so this might not be the highest priority investigation.

**Comment by floatplane** [comment]
Closing this as there's nothing actionable, the Sentry errors haven't recurred
