### ISSUE TITLE
Observations is being carried into two lines on android

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#513]
![Screenshot_20231101-125228_Avy](https://github.com/NWACus/avy/assets/119702342/c53eca9a-0d49-4d58-930b-26cece676956)

**Comment by charlotteguard** [comment]
Ok - I'm not that familiar with android. I am able to correct for this by changing my font size but I think I was on default.

**Comment by floatplane** [comment]
fixed in #518
