### ISSUE TITLE
Photos not working in offline mode (iOS)

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#516]
When I select a photo in offline mode it doesn't come through - shows as selected in my photo library but then doesn't show isn't displaying when I go back to the main ob.

**Comment by floatplane** [comment]
@charlotteguard can you paste in your app version? (Go to Menu -> About Avy, scroll to bottom, hit copy)

**Comment by charlotteguard** [comment]
Avy version 1.0.0 (56)
Git revision b6d060c3bcc60a958c124beda2c357acb064452d
Update ea762ad6-d3f4-408a-80a9-03442ffd4732 (preview)

**Comment by floatplane** [comment]
@charlotteguard I might need you to walk me through this, happy to jump on a call if that's better!

> then doesn't show isn't displaying when I go back to the main ob.

are you saying that the image doesn't show up on the submit ob form? or are you saying that you submitted the new ob, but the image isn't uploaded when you go back online?

**Comment by charlotteguard** [comment]
It doesn't show up back in the submit ob form. (nor when it is submitted when I go back online.)

**Comment by charlotteguard** [comment]
sorry I missed the first part  - happy to hop on a call!

**Comment by floatplane** [comment]
related: https://nwac.sentry.io/issues/4493002496/?project=4504317393436672&query=is:unresolved&stream_index=1

**Comment by charlotteguard** [comment]
Something to do with my phone version I think  (others can't reproduce). @floatplane made a change so I get an "unexpected error" toast. ideally we make the error not happen but pretty low priority.

**Comment by stevekuznetsov** [comment]
Hm - as much as users might not want anything more than "unexpected error" we ideally should be sending something through Sentry to track what the error actually was, or we're not going to be able to make any headway on this. @charlotteguard did you just try this today? I don't see any new Sentry events :|

**Comment by charlotteguard** [comment]
@stevekuznetsov I'm going to close this.. I have heard of some issues with offline obs but nothing I've been able to track down.
