### ISSUE TITLE
In observations - the add photos button is not pulling up the photo picker - Android 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#519]
The add photos button appears responsive but is not pulling up the photo picker in android

**Comment by floatplane** [comment]
@charlotteguard I added additional permission checking in last night's update - can you tell me if you now see this on Android?

<img width="384" alt="image" src="https://github.com/NWACus/avy/assets/101196/534cdac4-31c5-4d39-a624-f055bccacfe0">
