### ISSUE TITLE
How to handle nonconforming responses from API?

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#538]
Doing this in one hook - but no others - is going to surprise someone who is not expecting that. Perhaps update the schema if we're simply out-of-date or use a deny-list of nonconforming centers in the list?

_Originally posted by @stevekuznetsov in https://github.com/NWACus/avy/pull/537#discussion_r1383715332_

**Comment by stevekuznetsov** [comment]
We handled this by only loading the centers we need in the first pop-up for the app, and doing the full load for the dev menu.
