### ISSUE TITLE
Blindly applying expo doctor recommendations can create toxic updates

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#556]
This seemingly innocent PR https://github.com/NWACus/avy/pull/554 created an update that sent test builds into a death spiral on startup. The only way to resolve was to download a new app store build, but I had a nervous wait for that build to finish before I knew it was ok.

My interpretation of what happened is that the new `expo-*` packages referenced in that PR have a corresponding native update, and if you publish JS that takes a dependency on those packages then you're effectively declaring that the app binary has been built with the correct native versions.

The problem is compounded by the fact that we kick off builds and updates in parallel, and updates finish faster, so a bad update gets published and there's no way for users to resolve. Until the new build is ready, even an uninstall/reinstall cycle doesn't help, because they reinstall an old build and immediately download the toxic update again. 

Suggested resolution steps
- revert #554 
- treat expo doctor warnings as warnings, not errors. applying new package versions should be part of the steps when actively releasing new binaries, and not something that's done frequently

**Comment by stevekuznetsov** [comment]
`expo-dev-client` contains [native code](https://www.npmjs.com/package/expo-dev-client?activeTab=code). I think the statement is more general - we should be able to tell when any commit changes native code, and force that to bump the native runtime version.

**Comment by floatplane** [comment]
> we should be able to tell when any commit changes native code, and force that to bump the native runtime version

linting yarn.lock changes against that concept would be ideal, not sure how many different ways there are for each package to structure their internals though. I don't know if they have to have `ios` and `android` directories, for example. but that'd be better than nothing!

**Comment by floatplane** [comment]
Running against dev builds instead of Expo Go would also have demonstrated this problem immediately, and is considered an Expo best practice.

**Comment by stevekuznetsov** [comment]
In general, this issue describes the failure mode that occurs when we issue an OTA with changes to native code; there's no immediate work to be done here - we simply need to be more diligent in which updates we issue when.
