### ISSUE TITLE
`releaseChannel` on PostHog is always `default`

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#557]
This makes it impossible to write rules that target test builds vs. release builds. Culprit:

https://github.com/NWACus/avy/blob/8b12cf9fa2146df56842febe2b004b705fb5a753/components/KillSwitchMonitor.tsx#L44

Should be `Updates.channel || 'development'`

**Comment by stevekuznetsov** [comment]
Yep, looks like `releaseChannel` is the wrong value - `channel` is for updates.

**Comment by stevekuznetsov** [comment]
Might be good to name the PostHog value `channel` as well for clarity
