### ISSUE TITLE
hard to select west slopes north on map

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#604]
Just started using the Avy app. From the home page (the map), I'm having trouble successfully selecting the west slopes north zone. I have to tap on the far left side for it to work. If I tap in the middle nothing happens. I suspect this is the "North Cascades National Park" label from the underlying Google map layer that is blocking my tap.

Similar issue in West Central (with the national forest label) and Olympics (National Park). The other zones don't seem to have any issues since there are no labels at the default zoom level.

I hope this makes sense. I attached a screenshot. Green is the area that seems to work (hard to press, especially with gloves!) and red does nothing.

App and phone info below

Avy version 1.0.4 (76)
Build date 2023.12.01.00.41

Git revision 4663358
Update group ID 0b8af6fd-5147-4211-a6d3-96a7c69f5029 (channel: release)
Update ID c246d52a-ba84-403f-9de1-2eabb7dd5f93 (platform: android)

Pixel 5
Android 14
![Screenshot_20231130-204027](https://github.com/NWACus/avy/assets/119702342/d6ae7c3b-524f-4797-b15e-84f5f1086ff4)

**Comment by floatplane** [comment]
this is indeed #77. Polygons sit below map labels in the touch hierarchy and AFAICT there's no way to change that.

maybe we could remove the press handlers from the polygons and have a single press handler set on the map? might work?

**Comment by stevekuznetsov** [comment]
Going to try to pick this one up today

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/NWACus/avy/pull/613
