### ISSUE TITLE
Avalanche Problem Size Number-Line Incorrectly Rendering

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#61]
From this data (West Central, 1/11):

```
$ curl -s https://api.avalanche.org/v2/public/product/116908 | jq '.forecast_avalanche_problems[0].size'
[
  "1",
  "2"
]
```

The website does this:

![Screenshot from 2023-01-11 07-19-47](https://user-images.githubusercontent.com/7328370/211829565-b68480aa-cb39-4570-95ec-96c2b85cc767.png)

Our app does this:

![File (1)](https://user-images.githubusercontent.com/7328370/211829865-39b7e971-2c86-46c4-8fde-fba919fb1854.jpg)

**Comment by stevekuznetsov** [comment]
cc @floatplane

**Comment by yuliadub** [comment]
fixed with https://github.com/NWACus/avy/pull/376?
