### ISSUE TITLE
Weather fx not loading 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#628]
We got this email this am but reproduces on my a Droid phone: 

"Weather Forecast page does not load for any region on iPad is 17.1.2.  Same for iPhone iOS 17.1.2. 

I use the horizontal nav bar on the avy page - observations and Avalanche links 100%.  Last week ago, this was not an issue.

 Using mobile devices from the web page, I can access weather forecast."

**Comment by stevekuznetsov** [comment]
Looks like the zone IDs changed again. So much for assuming those were going to be static forever.
