### ISSUE TITLE
Location Picker Styling Malformed Once Location Chosen

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#630]
![File (35)](https://github.com/NWACus/avy/assets/7328370/b763a6c5-689d-484d-a940-fe2387f6b22c)

cc @floatplane

**Comment by floatplane** [comment]
that looks like an incredibly misleading degree of precision 😂 

https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude suggests that 9 digits of precision gets you within 110 microns...so at this level we've basically identified a proton...or maybe a quark 🤣 

I would suggest that we should maybe round these values to 4 or 5 digits after the decimal point
