### ISSUE TITLE
User not seeing year end campaign 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#648]
None of the year end graphics are displaying on at least this phone even though the feature flag is rolled out. 

Avy version 1.0.4 (76)
Build date 2023.12.21.01.12
Git revision f1f7dbe
Update group ID b2342de7-b898-4e55-b620-a241487fa6f1 (channel: release)
Update ID 21e9ecac-b5ec-4e0d-a052-d9713e2b355c (platform: ios)
User ID 619b8036-8f21-4f66-a780-e4ee83a8d928

**Comment by yuliadub** [comment]
I do see them on my phone

Avy version 1.0.4 (76)
Build date 2023.12.21.01.12
Git revision f1f7dbe
Update group ID b2342de7-b898-4e55-b620-a241487fa6f1 (channel: release)
Update ID 21e9ecac-b5ec-4e0d-a052-d9713e2b355c (platform: ios)
User ID 2ab4f795-c9e7-44bb-94a6-6e07e62f157b
