### ISSUE TITLE
Stuck on startup

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#667]
This has happened to me a few times, basically open the app after not opening it for a while and it just stuck on the initial loading page (blue screen with logo) I have to force quit the app and restart and it works fine. Happened to me at 12:12pm PST on 1/28

**Comment by stevekuznetsov** [comment]
Unfortunately if you are seeing a screen with only the logo and no other loading spinners, etc - that's just the splash screen for Android loading the app, and the app code is not even running yet. We'd need to look into what we could do to make loading better - maybe our bundle size is too large?
