### ISSUE TITLE
Size text not bolded 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#672]
![IMG_3772](https://github.com/NWACus/avy/assets/119702342/555a4f28-056f-449d-a0d2-d131b9e26221)
I can't repro this but Dallas sent it over. I think I saw that it was already noted somewhere? 

The size of the avalanche "Large (D2)" isn't bolded

**Comment by stevekuznetsov** [comment]
Yes, this was fixed in https://github.com/NWACus/avy/pull/649 - should be in the OTA we're publishing this evening. I'll close this out and if we see it again let's re-open, if that's ok.
