### ISSUE TITLE
PcpSum in 3100 cut off 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#673]
![Screenshot_20240201_145337 (1)](https://github.com/NWACus/avy/assets/119702342/4d40d833-9000-45b1-8e1f-627a0b7636c0)

**Comment by yuliadub** [comment]
looks like a dup of https://github.com/NWACus/avy/issues/642#issue-2047384757

**Comment by charlotteguard** [comment]
Hmm I thought it was a different column the time before but appears to be the same. It's still an issue for me.
