### ISSUE TITLE
Map labels are intercepting touches

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#77]
Example: in the West Slopes Central region, tapping on the "Mt Baker-Snoqualmie NF" label doesn't open the region forecast.

Observed on Android, not sure if this is universal.

**Comment by floatplane** [comment]
Also very hard to tap Mt Hood in the default view

**Comment by stevekuznetsov** [comment]
Just to confirm - you mean the text in the Google Maps view that literally says "Mt. Baker-Snoqualmie National Forest", right?

**Comment by floatplane** [comment]
Yeah! Are you seeing this or is it just me?

**Comment by stevekuznetsov** [comment]
Yep, reproduces on my end. When we handle #48 I think we will be able to fix this as well, might need to make sure we intercept `onPoiClick` and `onMarkerPress` and `onCalloutPress` in addition to `onPress`.

**Comment by floatplane** [comment]
this doesn't repro on iOS, FWIW

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/NWACus/avy/pull/613
