### ISSUE TITLE
Avalanche Obs Date discrepancy 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#772]
When a forecaster submits an avalanche observation they have the option of adding:

- Date observed, occurrence date, occurrence time, date accuracy, and time accuracy. 
- in the same avalanche ob on the website  this is displayed as "occurrence date (estimated)" and "Observation date" 
- In the app under the avalanche description we just show "date" with no indicator if it's the occurrence or observation date 
- And for the avalanche observation attached the date displayed in the app doesn't match any of the dates (occurrence date, avalanche ob date, or date of the observation it was attached to)
- Additionally, the app shows 5:00pm as the time but none of the date fields are populated on the oritional avalanche ob 

what is the logic for the current time and date field on an avalanche ob in the app?  Also need to think through this in the wider context of how to display avalanche obs in the app.

<img width="586" alt="Screenshot 2024-08-12 150009" src="https://github.com/user-attachments/assets/edf5ed36-5070-447b-a3c3-288df9540f06">

![Media](https://github.com/user-attachments/assets/59f04ffc-975f-4619-8847-2e87f273625c)

**Comment by charlotteguard** [comment]
@yuliadub this is the ob where the date is off: https://nwac.us/observations/#/view/observations/b9a57a4f-c7ae-4579-be30-357df55ba763

**Comment by yuliadub** [comment]
here is the json response from the AFP for this observation

`{
    "id": "b9a57a4f-c7ae-4579-be30-357df55ba763",
    "center_id": "nwac",
    "obs_source": "dashboard",
    "created_at": "2024-05-07T19:06:41.759260+00:00",
    "last_updated": "2024-08-12T21:45:44.333557+00:00",
    "status": "published",
    "observer_type": "forecaster",
    "organization": "Northwest Avalanche Center",
    "organization_url": null,
    "name": "Josh Hirshberg",
    "show_name": true,
    "start_date": "2024-05-07",
    "end_date": null,
    "activity": [
        "walking"
    ],
    "location_point": {
        "lat": 47.988,
        "lng": -120.357
    },
    "location_name": "North Fork 25 Mile Creek",
    "route": "Drove dirt roads to 6,000ft on Grouse mtn. Walked dry SE-SW slopes.",
    "instability": {
        "cracking": false,
        "collapsing": false,
        "avalanches_caught": false,
        "avalanches_observed": true,
        "avalanches_triggered": false,
        "cracking_description": "",
        "collapsing_description": ""
    },
    "instability_summary": "",
    "observation_summary": "",
    "media": [
        {
            "id": 1,
            "url": {
                "large": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-large.jpg",
                "medium": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-medium.jpg",
                "original": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996.jpg",
                "thumbnail": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-thumbnail.jpg"
            },
            "type": "image",
            "title": null,
            "caption": "(5/7/2024) <p>A natural D1.5 avalanche likely occurred on Monday, 5/6. Crescent Hill, 5,600ft, ESE</p> Photo: Josh Hirshberg",
            "favorite": false
        },
        {
            "id": 2,
            "url": {
                "large": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007866_663a3c518254b-large.jpg",
                "medium": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007866_663a3c518254b-medium.jpg",
                "original": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007866_663a3c518254b.jpg",
                "thumbnail": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007866_663a3c518254b-thumbnail.jpg"
            },
            "type": "image",
            "title": null,
            "caption": "(5/7/2024) <p>Plowed road through a lingering wind feature near the Chesapeake Saddle on Grouse Mtn. 5,600ft, SE</p> Photo: Josh Hirshberg",
            "favorite": false
        },
        {
            "id": 3,
            "url": {
                "large": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007868_663a78e496a41-large.jpg",
                "medium": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007868_663a78e496a41-medium.jpg",
                "original": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007868_663a78e496a41.jpg",
                "thumbnail": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007868_663a78e496a41-thumbnail.jpg"
            },
            "type": "image",
            "title": null,
            "caption": "<p>(5/7/2024)</p>\n<p>Snow cover lingers on northerly aspects above 5,000ft. Slide Ridge, Chelan Mtns</p>\n<p>Photo: Josh Hirshberg</p>",
            "favorite": false
        }
    ],
    "urls": [],
    "avalanches_summary": "Observed a recent D1.5 avalanche due to warming of storm snow",
    "advanced_fields": {
        "id": "e3dcce15-69e5-4d82-8597-2c5b10e0b1ba",
        "observation_id": "b9a57a4f-c7ae-4579-be30-357df55ba763",
        "observed_terrain": null,
        "time_in_field": {
            "end": "",
            "start": ""
        },
        "weather_summary": "Clear skies becoming partly cloudy. Moderate winds with gusts to 40mph in the AM. Overnight low below freezing  with hi in the low 40's at 6k feet.",
        "weather": {
            "air_temp": "",
            "cloud_cover": "few",
            "wind_loading": "unknown",
            "rain_elevation": "",
            "recent_snowfall": "",
            "snow_avail_for_transport": "small smounts"
        },
        "avalanche_comments": null,
        "snowpack_summary": "",
        "snowpack": null,
        "snowpack_media": [],
        "avalanche_problems": [],
        "avalanche_problems_comments": "",
        "terrain_use": null,
        "bottom_line": null
    },
    "avalanches": [
        {
            "id": "e17df22b-e0e5-43eb-b517-c5c4450773c9",
            "observation_id": "b9a57a4f-c7ae-4579-be30-357df55ba763",
            "status": "published",
            "created_at": "2024-05-07T18:48:20.382633+00:00",
            "last_updated": "2024-05-07T19:07:02.547480+00:00",
            "submitted_at": "2024-05-07T18:48:20.382633+00:00",
            "observer_type": "forecaster",
            "organization": "Northwest Avalanche Center",
            "center_id": "nwac",
            "obs_source": "dashboard",
            "forecaster_verified": true,
            "forecaster_edited": false,
            "forecaster_edited_reason": null,
            "name": "Josh Hirshberg",
            "show_name": true,
            "obs_date": "2024-05-07",
            "date": "2024-05-06",
            "date_known": false,
            "time": null,
            "time_known": false,
            "location_point": {
                "lat": 47.979,
                "lng": -120.397
            },
            "location_name": "Crescent Hill, Chelan mtns",
            "number": 1,
            "aspect": "SE",
            "aspect_range": [
                "E"
            ],
            "elevation": 5750,
            "avalanche_type": "WL",
            "avalanche_problem": null,
            "trigger": "N",
            "cause": null,
            "bed_sfc": null,
            "avg_crown_depth": null,
            "d_size": "1.5",
            "r_size": null,
            "weak_layer_date": null,
            "weak_layer_type": null,
            "width": null,
            "vertical_fall": null,
            "slope_angle": null,
            "terminus": null,
            "media": [
                {
                    "id": 1,
                    "url": {
                        "large": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-large.jpg",
                        "medium": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-medium.jpg",
                        "original": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996.jpg",
                        "thumbnail": "https://avalanche-org-media.s3.us-west-2.amazonaws.com/1000007867_663a3c44c6996-thumbnail.jpg"
                    },
                    "type": "image",
                    "title": null,
                    "caption": "(5/7/2024) <p>A natural D1.5 avalanche likely occurred on Monday, 5/6. Crescent Hill, 5,600ft, ESE</p> Photo: Josh Hirshberg",
                    "favorite": false
                }
            ],
            "attachment_url": null,
            "attachment_description": null,
            "comments": "Viewed from across the valley. Likely due to sun warming recent snow. Uncertain of exact problem/type.",
            "humans_caught": 0,
            "humans_part_buried_non_crit": 0,
            "humans_part_buried_crit": 0,
            "humans_fully_buried": 0,
            "humans_injured": 0,
            "humans_killed": 0,
            "vehicles_hit": 0,
            "vehicles_fully_buried": 0,
            "vehicles_damaged": 0,
            "vehicles_damage_cost": 0,
            "structures_hit": 0,
            "structures_damaged": 0,
            "structures_destroyed": 0,
            "structures_damage_cost": 0,
            "impacts_comments": null
        }
    ]
}`

looks like there are the following dates for the avalanche portion: 

            "obs_date": "2024-05-07",
            "date": "2024-05-06",

            "created_at": "2024-05-07T18:48:20.382633+00:00",
            "last_updated": "2024-05-07T19:07:02.547480+00:00",
            "submitted_at": "2024-05-07T18:48:20.382633+00:00",

I do not see May 5th anywhere in the response from the NAC which is weird.... What I did notice is that 

        "time_in_field": {
            "end": "",
            "start": ""
        },

in the avalanche is null.

Need to dig more into what the app is doing and will update here. But this does look like a misconception on the app end vs AFP giving us an unexpected date.

**Comment by stevekuznetsov** [comment]
This gets filed in the long list of "a point in time must include a date, a time _and a timezone_" ... 2024-05-06 00:00 UTC is 2024-05-05 17:00 PST.

**Comment by stevekuznetsov** [comment]
Just to expand on that ...

```
        "date": "2024-05-06",
```

This is an insufficient amount of precision. The sixth of August, for whom? Where in the world? From what vantage point? Midnight on the 6th of August in Washington state looks different from Japan :). In order to format this date correctly on devices in any time zone, we need to assume the time of day and the time zone.

Compare this to the storage for the dates around editing, submitting:

```
        "submitted_at": "2024-05-07T18:48:20.382633+00:00",
```

That precisely designates the date (`2024-05-07`), time (`18:48:20.382633`) and time zone (`+00:00`), which means it identifies an absolute moment in time and we can choose to format it in any way we wish, without having to assume anything.
