### ISSUE TITLE
Remove date field on avalanche obs unless specifically populated 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#773]
Related to this issue: https://github.com/NWACus/avy/issues/772

Time field shouldn't be included unless specifically populated - it's VERY rarely populated. 

An example of this also here: https://nwac.us/observations/#/view/observations/b9a57a4f-c7ae-4579-be30-357df55ba763

![IMG_2310 (1)](https://github.com/user-attachments/assets/3e479c6b-991e-4b5f-9713-bfb190445f03)

**Comment by stevekuznetsov** [comment]
I believe we're already doing this - on the web page for the linked observation the date is shown, since it is explicitly provided by the forecaster there.
