### ISSUE TITLE
Update Mt Washington AC Logo

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#798]
Fom Jeff @ Mt. washington center: I just noticed that the AC App has our old logo. I've attached our new logo, can you swap? I can provide other formats too if needed. Thanks!

I added the logos here:
https://drive.google.com/drive/u/0/folders/1hzVsJK8FS9flekXicucm6ghqXEjRlxFV?ths=true

**Comment by yuliadub** [comment]
@charlotteguard can they give us a png? maybe we can generate that from the .ai file but I am not savvy enough :D

**Comment by stevekuznetsov** [comment]
I think they were just PNG before on their websites, but I have an Adobe subscription as well and can mess around in Photoshop to trim things and reformat as necessary.

**Comment by charlotteguard** [comment]
https://drive.google.com/file/d/12UFEFiipGPaQ8UgZRQxyklzrYpSHBQru/view?usp=sharing
