### ISSUE TITLE
Share button for obs

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#807]
https://docs.google.com/document/d/1mS_asdSoeJl6QNZtSwwJ6d_9DqY7LdJwagMvZzF651c/edit?usp=sharing

https://www.figma.com/file/Bai2w7x0vUakL5WRjPGRg7/AVY-Native-App?type=design&node-id=2554%3A116&mode=design&t=UlMAADjCMOVcgBT4-1

**Comment by yuliadub** [comment]
why are these getting closed? does it have to do with which category its in or someting?

**Comment by stevekuznetsov** [comment]
@yuliadub it was a misconfiguration on the project, it should be fixed now

**Comment by stevekuznetsov** [comment]
Marking as done, we have a second issue for follow-ups.
