### ISSUE TITLE
Change avalanche forecast dropdowns to default open

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#841]
Right now you need to hit the carrot to expand the sections, rather all sections should be default open. This was feedback we got from both pros and recs that for at least their first visit they wanted them to be default open with the option to close when they finished reading.

**Comment by charlotteguard** [comment]
Not the outlook for the following day but expanded problems & discussion

**Comment by stevekuznetsov** [comment]
Broke in a bump of the dependency, fixed now.
