### ISSUE TITLE
Issue with obs submission

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#844]
From Zach Guy at CBAC: Hey Charlotte, we’ve had several people tell us that when they try to submit an observation using the app, nothing happens. We have yet to get an observation, and I just tried it this morning and had the same issue. When I fill out the form, and then hit the submit button, nothing happens. I’m heading into the field right now, but happy to troubleshoot tomorrow or whenever! Thanks for your help. 

I tried to repro and for me the location selection isn't work which is a required field so I can't get submit to go through.

**Comment by stevekuznetsov** [comment]
I can't reproduce the issue getting location selection to work on any platform (attempted on iOS, Android, both on the production app, preview app, and Expo Go). I can see that the "submit" button does nothing, need to look into this. I hope the new architecture didn't break our background controller.
